dist: trusty
sudo: false
os: linux

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    
script:
  - npm run test-headless

