dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

services:
  - docker

branches:
  only:
  - master
before_install: sudo -E -y apt-get install google-chrome-stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable --allow-unauthenticated

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test-headless
  - make travis