dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

services:
  - docker

branches:
  only:
  - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test-headless
  - make travis